export const enum StandardAttribute {
  ADDRESS = 'address',
  BIRTHDATE = 'birthdate',
  EMAIL = 'email',
  FAMILY_NAME = 'family_name',
  GENDER = 'gender',
  GIVEN_NAME = 'given_name',
  LOCALE = 'locale',
  MIDDLE_NAME = 'middle_name',
  NAME = 'name',
  NICKNAME = 'nickname',
  PHONE_NUMBER = 'phone_number',
  PICTURE_URL = 'picture',
  PREFERRED_USERNAME = 'preferred_username',
  PROFILE_URL = 'profile',
  TIMEZONE = 'zoneinfo',
  LAST_UPDATE_TIME = 'updated_at',
  WEBSITE = 'website',
}